### ISSUE TITLE
Add Bestaudio + Bestvideo to the download formats.

### ISSUE THREAD

**Issue by wpzzz** [Stormiix/converter-api#7]
like this
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

**Comment by Stormiix** [comment]
yeh I'm thinking About adding it to the formats list, Best Audio + Best Video.

**Comment by Stormiix** [comment]
@wpzzz  the format you specified is invalid it returns "ERROR: requested format not available"
